name: CI

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: blog
  RUN_REGION: europe-west1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy to GCR

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Print gcloud info
      - name: Info
        run: gcloud info

      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: yarn install --legacy-peer-deps
      - run: yarn lint
      - run: yarn build

      - run: yarn make
      - run: yarn push

      # Deploy image to Cloud Run
      - name: Deploy
        id: deploy
        run: |-
          gcloud run deploy jflow \
            --quiet \
            --region "$RUN_REGION" \
            --image "docker.io/huangjien/jflow:latest" \
            --platform "managed" \
            --port 8080 \
            --allow-unauthenticated

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
